import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), 'src')))
from database_manager import DatabaseManager
from decorators import immutable_fields

class TestDatabaseManagerConcrete(DatabaseManager):
    def get_column_id(self): ...

    def _create_table(self): ...
    
    def insert_row(self, *args): ...
    
    def update_row(self, record_id, **kwargs): ...

    def delete_row(self, record_id): ...

    def get_by_id(self, record_id): ...