from enum import Enum 

class Tables(Enum): 
    PRODUCTPROFILE = 1
    VMPROFILE = 2
    USERPROFILE = 3
    OWNERPROFILE = 4
    COMPLAINTPROFILE = 5
    COMMENTPROFILE = 6
    PRODUCT_VM = 12
    VM_OWNER = 24
    COMPLAINT_VM = 54
    COMMENT_PRODUCT_USER = 613